default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: studio_hall_pagamento_development
  username: studio_hall
  password: <%= ENV["DATABASE_PASSWORD"] %>

test:
  <<: *default
  database: studio_hall_pagamento_test

production:
  <<: *default
  database: studio_hall_pagamento_production
  username: studio_hall_pagamento
  password: <%= ENV["DATABASE_PASSWORD"] %>
